name: pbkdf2
description: An implementation of the Password-Based Key Derivation Function 2 (PBKDF2) mechanism. (RFC 8018)
version: 1.0.3
repository: https://github.com/carlosmakin/pbkdf2

environment:
  sdk: ^3.8.0

dependencies:
  benchmark_harness: ^2.3.1
  crypto: ^3.0.6

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
